location          = "South Africa North"
resource_prefix   = "epicbook-prod"
vm_size           = "Standard_B2ats_v2"
admin_username    = "azureuser"
admin_password    = "EpicBook@2026"
db_name           = "bookstore"
db_user           = "epicbook_user"
db_password       = "EpicDB@2026!"